version: '3'
services:
  detectron:
    build: .
    image: detectron-test
    volumes:
    # NOTE: change to apporiate file destination (ie. what your system is)
      - /RemoteDockerFiles/PatrickWorkstation/AutomatedTUGTest/:/opt/project/
      - /RemoteDockerFiles/PatrickWorkstation/AutomatedTUGTest/included_files/:/included_files/
      - /RemoteDockerFiles/PatrickWorkstation/AutomatedTUGTest/output/:/output/

    # to gain access to terminal
#    entrypoint: /bin/sh
#    stdin_open: true
#    tty: true